<a href="https://colab.research.google.com/github/bshakhruz/pytorch/blob/main/numpy_vs_tensor.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [11]:
import torch
import numpy as np

**List**

In [2]:
my_list = [[1,2,3],[4,5,6]]
my_list

[[1, 2, 3], [4, 5, 6]]

**Numpy Arrays**

In [12]:
np1 = np.random.rand(3,4)
np1

array([[0.08482762, 0.71498769, 0.02477098, 0.21232837],
       [0.91074582, 0.09329068, 0.20768044, 0.63838924],
       [0.48127178, 0.23825073, 0.98438653, 0.19814743]])

In [13]:
np1.dtype

dtype('float64')

**Tensors**

In [15]:
tensor_2d = torch.randn(3,5)
tensor_2d

tensor([[-0.3643, -1.5512, -0.8596,  1.3706,  0.8905],
        [ 2.6750,  1.9795, -0.7772, -0.6550,  2.1039],
        [-0.2163,  0.3169,  1.5353,  1.4982, -0.8749]])

In [16]:
tensor_2d.dtype

torch.float32

In [18]:
tensor_3d = torch.zeros(3,2,4)
tensor_3d

tensor([[[0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.]]])

In [20]:
# Create a tensor out of numpy
my_tensor = torch.tensor(np1)
my_tensor

tensor([[0.0848, 0.7150, 0.0248, 0.2123],
        [0.9107, 0.0933, 0.2077, 0.6384],
        [0.4813, 0.2383, 0.9844, 0.1981]], dtype=torch.float64)