<a href="https://colab.research.google.com/github/bshakhruz/pytorch/blob/main/slicing.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import torch

In [6]:
my_torch = torch.arange(1,11)
my_torch

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [8]:
# Reshape and View
my_torch = my_torch.reshape(2,5)
my_torch

tensor([[ 1,  2,  3,  4,  5],
        [ 6,  7,  8,  9, 10]])

In [10]:
# Use negative 1 if you don't know what the list you are working
my_torch2 = torch.arange(1,15)
my_torch2

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [12]:
my_torch2 = my_torch2.reshape(2,-1)
my_torch2

tensor([[ 1,  2,  3,  4,  5,  6,  7],
        [ 8,  9, 10, 11, 12, 13, 14]])

In [13]:
# Slicing & Indexing
my_torch7 = torch.arange(1,11)
my_torch7

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [14]:
my_torch7[4]

tensor(5)

In [16]:
my_torch8 =my_torch7.reshape(5,-1)
my_torch8

tensor([[ 1,  2],
        [ 3,  4],
        [ 5,  6],
        [ 7,  8],
        [ 9, 10]])